### ISSUE TITLE
Admin console will not be started automatically

### ISSUE THREAD

**Issue by gigazine-dev** [element-hq/ess-starter-edition-core#7]
**Describe the bug**
I followed these steps: [Single Node Installations](https://ems-docs.element.io/books/element-on-premise-documentation/page/single-node-installations)
After the installation had finished, I tried to log in via `http://<server IP>:8443/admin/users` and got these errors:

```
_app-47c398430144ae83.js:21 
       POST https://admin.<server address>/_matrix/client/v3/login 403 (Forbidden)
eO._end @ _app-47c398430144ae83.js:21
eO.end @ _app-47c398430144ae83.js:21
（匿名） @ _app-47c398430144ae83.js:21
ef.then @ _app-47c398430144ae83.js:21
```

```
There was an error automatically logging in: Error: {"errcode":"M_FORBIDDEN","error":"Invalid username or password"}
    at eO.<anonymous> (_app-47c398430144ae83.js:21:14241)
    at en.emit (_app-47c398430144ae83.js:12:24813)
    at XMLHttpRequest.<anonymous> (_app-47c398430144ae83.js:21:18168)
```

And I could not access the admin page.
![snap4266](https://github.com/vector-im/ess-starter-edition-core/assets/43030702/3002324d-3db4-4c3a-8636-971fc8494a1c)

I checked the pods and noticed the `synapse-admin-ui` pod was not running.
Is any action needed to start admin UI?

Thank you in advance.

**Comment by hanthor** [comment]
Is this for Starter Edition (downloaded from ems.element.io) or Starter Edition Core (this repo)?

**Comment by gigazine-dev** [comment]
I downloaded the binary from ems.element.io: `element-installer-starter-edition-23.10.04-gui.bin`

**Comment by RichardHeilmann** [comment]
We are having the same problem with the Element Starter Edition.
On the https://element.io/pricing page, the "Admin Console" is listed as a feature.
After installation of element-installer-starter-edition-24.04.01-gui.bin, downloaded from https://ems.element.io/on-premise/download, the Admin Console is missing.
I already tried to contact Element about this via support@element.io and contact@element.io, but did not get an answer yet.

**Comment by RichardHeilmann** [comment]
@gigazine-dev

I just got confirmation that the free Element Starter edition, the one you can download from ems.element.io, does NOT include the Admin Console.
You need to administrate users and groups via command line.

**Comment by sanamustafa123** [comment]
Could you please share where I can find the command line tools? Thank you!

**Comment by sanamustafa123** [comment]
Could you please share where I can find the command line tools? Thank you!

**Comment by happyyyme** [comment]
Could you please share where I can find the command line tools? Thank you!

**Comment by happyyyme** [comment]
@gigazine-dev Could you please share where I can find the command line tools? Thank you!

**Comment by happyyyme** [comment]
@RichardHeilmann Could you please share where I can find the command line tools? Thank you!
